server:
  port: 5475

spring:
  application:
    name: trading-platform-api
  datasource:
    url: jdbc:postgresql://localhost:5432/trading
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#custom application properties
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
